
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  generateName: bootcamp-app-run-
spec:
  serviceAccountName: build-bot
  params:
    - name: app-name
      value: bootcamp-app
    - name: github-repo
      value: https://github.com/cloud-native-garage-method-cohort/buildah-assignment-William-Fred
    - name: image-repo
      value: quay.io/william_chan1_ibm/bootcamp-app
  pipelineRef:
    name: bootcamp-app
  workspaces:
  - name: pipeline-shared-data
    volumeClaimTemplate:
      spec:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi