apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

images:
- name: '*'
  newName: quay.io/william_chan1_ibm/bootcamp-app 
  newTag: 5c3cca69c4b2b0af9ba625436539dbd88842c701

resources:
- deployment.yaml
- service.yaml
- route.yaml
